# docker-compose.yml
version: "3.8"

services:
  web:
    image: joysonestibeiro/lizmap-volcano:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - ./projects:/srv/projects
      - ./lizmap-config:/var/www/webapp/var/config
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:13-3.1
    restart: always
    environment:
      POSTGRES_DB: lizmap
      POSTGRES_USER: lizmap
      POSTGRES_PASSWORD: lizmap
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
