services:
  - type: web
    name: lizmap-volcano-map3
    env: docker
    plan: free
    dockerPath: ./docker-compose.yml
    buildFilter:
      paths:
        - docker-compose.yml
        - .env
        - render.yaml
        - projects/**
        - lizmap-config/**
    autoDeploy: true

